# Number of days of inactivity before an issue becomes stale
daysUntilStale: 1

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 1

# pulls/issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security

# Label to use when marking an issue as stale
staleLabel: stale

# Set to true to ignore pulls/issues in a project (defaults to false)
exemptProjects: false

# Set to true to ignore pulls/issues in a milestone (defaults to false)
exemptMilestones: false

# Set to true to ignore pulls/issues with an assignee (defaults to false)
exemptAssignees: false

# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  The end.

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30
